---
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
Name: mysite
After: 'framework/*','cms/*','silverstripe-cacheinclude/*'
---
SSViewer:
  theme_enabled: false
MySQLDatabase:
  connection_charset: 'utf8'
GDBackend:
  default_quality: 80
i18n:
  default_locale: 'nl_NL'
Date:
  nice_format: 'd-m-Y'
SS_Datetime:
  nice_format: 'd-m-Y G:i'
SiteTree:
  nested_urls: true
Email:
  admin_email: 'mail@mysite.com'
  bcc_all_emails_to: 'bram@xd.nl'
SmtpMailer:
  host: mail.mysite.nl
  user: mail@mysite.nl
  password: password
  encryption: tls
  charset: UTF-8
BetterNavigator:
    developers:
      - 'mail@mysite.com'
OpenGraph:
  application_id: ''  # Give application id or set this to 'SiteConfig' so the cms user can set this value
  admin_id: ''        # Give admin id or set this to 'SiteConfig' so the cms user can set this value
  default_locale: 'nl_NL'
  default_tagbuilder: 'OpenGraphBuilder'
ShareCare:
  twitter_username: 'YOUR_USERNAME'
#GoogleGeocoding:
#  google_api_key: 'YOUR_GOOGLE_SERVER_API_KEY'
Addressable:
  set_postcode_regex: '/^[0-9A-Za-z\s]+$/'
LeftAndMain:
  extra_requirements_css:
    - 'mysite/css/cms.css'
FormSpamProtectionExtension:
  default_spam_protector: NocaptchaProtector
NocaptchaField:
  site_key: 'YOUR_SITE_KEY'
  secret_key: 'YOUR_SECRET_KEY'
Page:
  default_image: '/favicon-152.png'
  default_slices:
    - PageContentSlice