---
Name: mySchemaConfig
---
Page:
  default_image: '/favicon-152.png'
  active_schema:
    - Broarm\Schema\Builder\LocalBusiness
    - Broarm\Schema\Builder\Website
    - Broarm\Schema\Builder\Breadcrumbs
BlogPost:
  active_schema:
    - Broarm\Schema\Builder\NewsArticle