---
Name: app
---
SilverStripe\Core\Manifest\ModuleManifest:
  project: app
SilverStripe\i18n\i18n:
  default_locale: 'nl_NL'
SilverStripe\View\SSViewer:
  rewrite_hash_links: false
SilverStripe\Control\Email\Email:
  admin_email:
    mail@mysite.com: 'app'
#  send_all_emails_from:
#    mail@mysite.com: 'app'
SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - 'app/client/dist/styles/cms.css'
SilverStripe\Forms\HTMLEditor\TinyMCEConfig:
  editor_css:
    - 'app/client/dist/styles/editor.css'
SilverStripe\SpamProtection\Extension\FormSpamProtectionExtension:
  default_spam_protector: UndefinedOffset\NoCaptcha\Forms\NocaptchaProtector
UndefinedOffset\NoCaptcha\Forms\NocaptchaField:
  site_key: 'YOUR_SITE_KEY'
  secret_key: 'YOUR_SECRET_KEY'
Symbiote\Addressable\Addressable:
  postcode_regex: '/^[0-9A-Za-z\s]+$/'
Symbiote\Addressable\GoogleGeocodeService:
  google_api_key: 'YOUR_GOOGLE_SERVER_API_KEY'
LeKoala\DebugBar\DebugBar:
  check_local_ip: false
  enabled_in_admin: false
  auto_debug: true
---
Except:
  environment: 'live'
---
SilverStripe\Control\Email\Email:
  send_all_emails_to: mail@mysite.com
